export const DEFAULT_CONFIG = {
  riskPerTrade: 0.25,
  dayMaxDrawdown: 2,
  swingMaxDrawdown: 3,
  positionMaxDrawdown: 4,
  dayMaxTrades: 4,
  rsiOversold: 10,
  rsiOverbought: 90,
  h4FibEntryMin: 50,
  h4FibEntryMax: 61.8,
  m5FibEntryMin: 50,
  m5FibEntryMax: 61.8,
  h4SetupRequired: true,
  h4BreakoutRequired: true,
  h4RetestRequired: true,
  m5ExecutionRequired: true,
  m5BreakoutRequired: true,
  m5FibonacciRequired: true,
  m5RetestRequired: true,
  m5FibZoneRequired: true,
  m1ConfirmationRequired: false,
  newsTradingAllowed: false,
  newsBlackoutEnabled: true,
  trailingProfitEnabled: true,
  paperTrading: true,
};

export const DERIV_SYMBOLS = [
  '1HZ10V',
  '1HZ25V',
  '1HZ50V',
  '1MBB100',
  '1MBB200',
  '1MBR100',
  '1MR100',
  'RNG100',
  'BOOM1000',
  'CRASH500',
  'JUMP100',
  'STEP',
];
